spring.application.name=paynest
spring.datasource.url=jdbc:postgresql://localhost:5433/paynest
spring.datasource.username=paynest
spring.datasource.password=paynest
spring.flyway.enabled=true
server.port=8090
