spring.application.name=paynest

server.port=8090

spring.datasource.url=jdbc:postgresql://localhost:5433/paynest

spring.datasource.username=paynest
spring.datasource.password=paynest

spring.flyway.enabled=true

spring.profiles.active=jpa

spring.jpa.hibernate.ddl-auto=validate

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.open-in-view=false

paynest.jwt.secret=73db5e3f0a450db7c5f92fb4788721bdc328704492372e7b84dc1b24713b784e
paynest.jwt.expiration-ms=900000
